### ISSUE TITLE
ERROR: Signature file is either missing or corrupt

### ISSUE THREAD

**Issue by lknittig-panw** [wwce/Assassin#20]
When exec python assassin.py get print of "Signature file is either missing or corrupt." 
entry in /var/log/secops/assassin.log
[assassin.log](https://github.com/wwce/Assassin/files/4458644/assassin.log)

2020-04-09 20:44:10,867 - assassinLogger - DEBUG - Signature file is either missing or corrupt

Beyond my knowledge but appears **servicesDetections.json** is now part of reporting.py included as LIB for assassin.py ..  

This appears to related to overall assassin reporting error of  "Shodan error: HTTP Error 404: NotFound" on any received host from Hacker Target routine.. then reporting.py errors out with:

Traceback (most recent call last):
  File "assassin.py", line 113, in <module>
    main()
  File "assassin.py", line 104, in main
    report_shodan(report, domain, ip, shodan, summary)
  File "/app/assassin/lib/reporting.py", line 407, in report_shodan
    if linkhost not in hosts:
NameError: name 'hosts' is not defined

assassin.log attached with test run against "paloaltonetworks.com"

**Comment by hotpeppersec** [comment]
Hi Lance! Good catch. Thanks so much for testing this. 

I think i have a fix for the issue but I am not sure what's going on with Shodan right now. I think 503 means they are down for maintenance or something. I will test again tomorrow and make sure it's working before I merge this one. 

If you want to test the fix yourself you can just change "serviceDetections.json" to "lib/serviceDetections.json" and that should do it. 
```
root@assassin:/app/assassin# python assassin.py 
Signatures loaded
What domain would you like to search (.com/.net)? big.net
Lookup big.net via Verisign
Hacker Target
Received 3 hosts from Hacker Target
Processing host: big.net
Shodan error: HTTP Error 503: Service Unavailable
Processing host: tahoe.big.net
Shodan error: HTTP Error 503: Service Unavailable
Processing host: sfpi.big.net
Shodan error: HTTP Error 503: Service Unavailable
```
