### ISSUE TITLE
reporting.py report_shodan if linkhost nost in hosts failures 

### ISSUE THREAD

**Issue by lknittig-panw** [wwce/Assassin#22]
When I attempt to run assassin on various test domain it always errors out with reporting.py in report_shodan if link host not in hosts: NameError: Name 'hosts' is not defined.. 

example: 
Processing host: www2.paloaltonetworks.com
Traceback (most recent call last):
  File "assassin.py", line 113, in <module>
    main()
  File "assassin.py", line 104, in main
    **report_shodan(report, domain, ip, shodan, summary)
  File "/app/assassin/lib/reporting.py", line 407, in report_shodan
    if linkhost not in hosts:
NameError: name 'hosts' is not defined**

**Comment by lknittig-panw** [comment]
reporting.py

 linkhost = line.lower().replace(">", "").replace("<", "").split('a href="')[
                                        1].split('"')[0].replace("http://", "").replace("https://", "").split("/")[0]

                                    if domain in linkhost:
                                        if linkhost not in hosts:
                                            print(
                                                "Discovered additional host from HTML link: %s" % (linkhost, ))
                                            hosts.append(
                                                linkhost)
                                    else:
                                        if not 'linkpivottargets' in summary:
                                            summary['linkpivottargets'] = [
                                            ]
                                        if linkhost not in summary['linkpivottargets']:
                                            summary['linkpivottargets'].append(
                                                linkhost)
                                            print(
                                                "New potential pivot from link: %s" % (linkhost, ))

**Comment by hotpeppersec** [comment]
Can you please run the test in docker, and once it fails do a `cp /var/log/secops/assassin.log /app`  so you can get a copy of the log to local file system? Then attach to this issue? I am not able to reproduce the error.

**Comment by lknittig-panw** [comment]
output: and attaching assassin.log

root@assassin:/app/assassin# python assassin.py
Signatures loaded
What domain would you like to search (.com/.net)? acxiom.com
Lookup acxiom.com via Verisign
Hacker Target
Received 186 hosts from Hacker Target
Combined to a total of 186 hosts
Processing host: acxiom.com
Traceback (most recent call last):
  File "assassin.py", line 118, in <module>
    main()
  File "assassin.py", line 108, in main
    report_shodan(report, domain, ip, shodan, summary)
  File "/app/assassin/lib/reporting.py", line 321, in report_shodan
    elif host in line:
NameError: name 'host' is not defined
